#ci-cd

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -55,11 +55,11 @@ jobs:
             npm install
 
             # Check if the .env.production file exists, otherwise exit
-            echo "Checking if .env.production file exists in /root/metal/.env/"
+            echo "Checking if env.production file exists..."
             ls -l /root/metal/.env/
 
-            if [ ! -f "/root/metal/.env/.env.production" ]; then
-              echo ".env.production file missing at /root/metal/.env/.env.production"
+            if [ ! -f ${{ env.ENV_FILE_PATH }} ]; then
+              echo ".env.production file not found"
               exit 1
             fi
 
@@ -67,6 +67,6 @@ jobs:
             cp /root/metal/.env/.env.production .env
 
             # Restart the application with PM2
-            pm2 delete "${APP_NAME}" || true
-            pm2 start npm --name "${env.APP_NAME}" -- run start
+            pm2 delete ${{ env.USERNAME }} || true
+            pm2 start npm --name ${{ env.USERNAME }} -- run start
             pm2 save
